language: python
# Select Trusty Tahr.
sudo: required
dist: trusty
git:
  # We need neither .heavy nor .secret
  # (.secret isn't available anyway)
  submodules: false
  depth: 3
python:
  - "3.5"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libav-tools npm rabbitmq-server coffeescript openssl
  - rm backend/credentials.py
  - openssl aes-256-cbc -K $encrypted_3804c810c01a_key -iv $encrypted_3804c810c01a_iv -in tools/minimal_sound/test-cred.py.enc -out backend/credentials.py -d
  - sudo rabbitmq-server -detached
  # Note that on Debian, you'd need to say 'pip3'
  - pip install pika pillow pydub tweepy typing
  # ( Skip rabbitmq_management, because Travis doesn't
  #   offer this kind of web interface anyway.)
  # - sudo rabbitmq-plugins enable rabbitmq_management
  # Build frontend for fun:
  # ( Only pulls frontend dependencies )
  - sudo ln -s /usr/bin/nodejs /usr/bin/node
  - make install_dependencies
  # By now, rabbitmq-server should be done starting up
  - sudo rabbitmqctl status
  - sudo rabbitmq-plugins enable --online rabbitmq_web_stomp
  # Set up a minimal environment without pulling "hot_heavy"
  - tools/minimal_sound/provide.sh
script:
  - make frontend
  # ( Makefile is currently unimplemented for backend )
  # Is rabbitmq running already?
  - ( cd backend && ./tests.py test_ben )
