language: python
# Select Trusty Tahr.
sudo: required
dist: trusty
git:
  # We need neither .heavy nor .secret
  # (.secret isn't available anyway)
  submodules: false
  depth: 3
python:
  - "3.5"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libav-tools npm rabbitmq-server openssl
  - rm backend/credentials.py
  - openssl aes-256-cbc -K $encrypted_3804c810c01a_key -iv $encrypted_3804c810c01a_iv -in tools/minimal_sound/test-cred.py.enc -out backend/credentials.py -d
  - sudo rabbitmq-server -detached
  # ( Skip rabbitmq_management, because Travis doesn't
  #   offer this kind of web interface anyway.)
  # - sudo rabbitmq-plugins enable rabbitmq_management
  # Build frontend for fun:
  # ( Only pulls frontend dependencies )
  - sudo ln -s /usr/bin/nodejs /usr/bin/node
  - make install_dependencies
  # By now, rabbitmq-server should be done starting up
  - sudo rabbitmqctl status
  - sudo rabbitmq-plugins enable --online rabbitmq_web_stomp
  #                              ^^^^^^^^ don't use with Debian; too old version
  # Set up a minimal environment without pulling "hot_heavy"
  - tools/minimal_sound/provide.sh
script:
  - make frontend
  - make pubweb
  # For fun, let's see which version is used on Travis.
  # Note: 2 means "old version, update needed"
  - ./tools/tweepy_monkeypatch/tell.sh || [ $? = 2 ]
  # Highly Travis-dependent:
  - sudo cp 'tools/tweepy_monkeypatch/after' '/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/tweepy/streaming.py'
  # Check again (but without any failure)
  - ./tools/tweepy_monkeypatch/tell.sh
  # ( Makefile is currently unimplemented for backend )
  # Is rabbitmq running already?
  - ( cd backend && ./tests.py test_ben )
